export const ADMIN_ROUTE = "/admin"

export const AUTH = "/auth"
export const REGISTRATION = "/registration"
export const MAIN_PAGE = "/"
export const QUIZ = "/quiz"
export const QUIZ_LIST = "/quiz_list"
export const MAIN_MENU = "/main_menu"
export const ABOUT = "/about"
export const ROUTE = "/admin"
export const NOT_FOUND = "/not_found"

export const ADMIN_AUTH = "/auth"
export const ADMIN_REGISTRATION = "/registration"
export const ADMIN_MAIN_PAGE = "/main"
export const ADMIN_QUIZ = "/quiz"
export const ADMIN_QUIZ_LIST = "/quiz_list"
export const ADMIN_MAIN_MENU = "/main_menu"
export const ADMIN_ABOUT = "/about"
